const PREVENT_EVENT = "event_prevent_default";

const TEAM_NONE = 0;
const TEAM_SPECTATOR = 1;
const TEAM_CT = 2;
const TEAM_T = 3;

const HUD_PRINT_TALK = 3
const HUD_PRINT_CONSOLE = 2
const HUD_PRINT_CENTER = 4

// const name by W4nder
const STEAM_USER_HIGH_VALUE = BigInt(76561197960265728)

const GAME_MESSAGE_TARGET_CONSOLE = 'console'
const GAME_MESSAGE_TARGET_HUD = 'hud'

export {
    PREVENT_EVENT,
    TEAM_NONE,
    TEAM_SPECTATOR,
    TEAM_CT,
    TEAM_T,
    HUD_PRINT_TALK,
    HUD_PRINT_CONSOLE,
    HUD_PRINT_CENTER,
    STEAM_USER_HIGH_VALUE,
    GAME_MESSAGE_TARGET_CONSOLE,
    GAME_MESSAGE_TARGET_HUD
}

export default {
    PREVENT_EVENT,
    TEAM_NONE,
    TEAM_SPECTATOR,
    TEAM_CT,
    TEAM_T,
    HUD_PRINT_TALK,
    HUD_PRINT_CONSOLE,
    HUD_PRINT_CENTER,
    STEAM_USER_HIGH_VALUE,
    GAME_MESSAGE_TARGET_CONSOLE,
    GAME_MESSAGE_TARGET_HUD
}