// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c_peer2peer_netmessages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_c_5fpeer2peer_5fnetmessages_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_c_5fpeer2peer_5fnetmessages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "netmessages.pb.h"
#include "networkbasetypes.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_c_5fpeer2peer_5fnetmessages_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_c_5fpeer2peer_5fnetmessages_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_c_5fpeer2peer_5fnetmessages_2eproto;
class CP2P_Ping;
struct CP2P_PingDefaultTypeInternal;
extern CP2P_PingDefaultTypeInternal _CP2P_Ping_default_instance_;
class CP2P_TextMessage;
struct CP2P_TextMessageDefaultTypeInternal;
extern CP2P_TextMessageDefaultTypeInternal _CP2P_TextMessage_default_instance_;
class CP2P_VRAvatarPosition;
struct CP2P_VRAvatarPositionDefaultTypeInternal;
extern CP2P_VRAvatarPositionDefaultTypeInternal _CP2P_VRAvatarPosition_default_instance_;
class CP2P_VRAvatarPosition_COrientation;
struct CP2P_VRAvatarPosition_COrientationDefaultTypeInternal;
extern CP2P_VRAvatarPosition_COrientationDefaultTypeInternal _CP2P_VRAvatarPosition_COrientation_default_instance_;
class CP2P_Voice;
struct CP2P_VoiceDefaultTypeInternal;
extern CP2P_VoiceDefaultTypeInternal _CP2P_Voice_default_instance_;
class CP2P_WatchSynchronization;
struct CP2P_WatchSynchronizationDefaultTypeInternal;
extern CP2P_WatchSynchronizationDefaultTypeInternal _CP2P_WatchSynchronization_default_instance_;
class CSteam_Voice_Encoding;
struct CSteam_Voice_EncodingDefaultTypeInternal;
extern CSteam_Voice_EncodingDefaultTypeInternal _CSteam_Voice_Encoding_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum CP2P_Voice_Handler_Flags : int {
  CP2P_Voice_Handler_Flags_Played_Audio = 1,
};

bool CP2P_Voice_Handler_Flags_IsValid(int value);
constexpr CP2P_Voice_Handler_Flags CP2P_Voice_Handler_Flags_Handler_Flags_MIN = static_cast<CP2P_Voice_Handler_Flags>(1);
constexpr CP2P_Voice_Handler_Flags CP2P_Voice_Handler_Flags_Handler_Flags_MAX = static_cast<CP2P_Voice_Handler_Flags>(1);
constexpr int CP2P_Voice_Handler_Flags_Handler_Flags_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
CP2P_Voice_Handler_Flags_descriptor();
template <typename T>
const std::string& CP2P_Voice_Handler_Flags_Name(T value) {
  static_assert(std::is_same<T, CP2P_Voice_Handler_Flags>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Handler_Flags_Name().");
  return CP2P_Voice_Handler_Flags_Name(static_cast<CP2P_Voice_Handler_Flags>(value));
}
template <>
inline const std::string& CP2P_Voice_Handler_Flags_Name(CP2P_Voice_Handler_Flags value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CP2P_Voice_Handler_Flags_descriptor,
                                                 1, 1>(
      static_cast<int>(value));
}
inline bool CP2P_Voice_Handler_Flags_Parse(absl::string_view name, CP2P_Voice_Handler_Flags* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CP2P_Voice_Handler_Flags>(
      CP2P_Voice_Handler_Flags_descriptor(), name, value);
}
enum P2P_Messages : int {
  p2p_TextMessage = 256,
  p2p_Voice = 257,
  p2p_Ping = 258,
  p2p_VRAvatarPosition = 259,
  p2p_WatchSynchronization = 260,
};

bool P2P_Messages_IsValid(int value);
constexpr P2P_Messages P2P_Messages_MIN = static_cast<P2P_Messages>(256);
constexpr P2P_Messages P2P_Messages_MAX = static_cast<P2P_Messages>(260);
constexpr int P2P_Messages_ARRAYSIZE = 260 + 1;
const ::google::protobuf::EnumDescriptor*
P2P_Messages_descriptor();
template <typename T>
const std::string& P2P_Messages_Name(T value) {
  static_assert(std::is_same<T, P2P_Messages>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to P2P_Messages_Name().");
  return P2P_Messages_Name(static_cast<P2P_Messages>(value));
}
template <>
inline const std::string& P2P_Messages_Name(P2P_Messages value) {
  return ::google::protobuf::internal::NameOfDenseEnum<P2P_Messages_descriptor,
                                                 256, 260>(
      static_cast<int>(value));
}
inline bool P2P_Messages_Parse(absl::string_view name, P2P_Messages* value) {
  return ::google::protobuf::internal::ParseNamedEnum<P2P_Messages>(
      P2P_Messages_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class CP2P_TextMessage final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CP2P_TextMessage) */ {
 public:
  inline CP2P_TextMessage() : CP2P_TextMessage(nullptr) {}
  ~CP2P_TextMessage() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CP2P_TextMessage(::google::protobuf::internal::ConstantInitialized);

  CP2P_TextMessage(const CP2P_TextMessage& from);
  CP2P_TextMessage(CP2P_TextMessage&& from) noexcept
    : CP2P_TextMessage() {
    *this = ::std::move(from);
  }

  inline CP2P_TextMessage& operator=(const CP2P_TextMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline CP2P_TextMessage& operator=(CP2P_TextMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CP2P_TextMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const CP2P_TextMessage* internal_default_instance() {
    return reinterpret_cast<const CP2P_TextMessage*>(
               &_CP2P_TextMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CP2P_TextMessage& a, CP2P_TextMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(CP2P_TextMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CP2P_TextMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CP2P_TextMessage* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CP2P_TextMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CP2P_TextMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CP2P_TextMessage& from) {
    CP2P_TextMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CP2P_TextMessage* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "CP2P_TextMessage";
  }
  protected:
  explicit CP2P_TextMessage(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 1,
  };
  // optional bytes text = 1;
  bool has_text() const;
  void clear_text() ;
  const std::string& text() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* ptr);

  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(
      const std::string& value);
  std::string* _internal_mutable_text();

  public:
  // @@protoc_insertion_point(class_scope:CP2P_TextMessage)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr text_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_c_5fpeer2peer_5fnetmessages_2eproto;
};// -------------------------------------------------------------------

class CSteam_Voice_Encoding final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSteam_Voice_Encoding) */ {
 public:
  inline CSteam_Voice_Encoding() : CSteam_Voice_Encoding(nullptr) {}
  ~CSteam_Voice_Encoding() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CSteam_Voice_Encoding(::google::protobuf::internal::ConstantInitialized);

  CSteam_Voice_Encoding(const CSteam_Voice_Encoding& from);
  CSteam_Voice_Encoding(CSteam_Voice_Encoding&& from) noexcept
    : CSteam_Voice_Encoding() {
    *this = ::std::move(from);
  }

  inline CSteam_Voice_Encoding& operator=(const CSteam_Voice_Encoding& from) {
    CopyFrom(from);
    return *this;
  }
  inline CSteam_Voice_Encoding& operator=(CSteam_Voice_Encoding&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CSteam_Voice_Encoding& default_instance() {
    return *internal_default_instance();
  }
  static inline const CSteam_Voice_Encoding* internal_default_instance() {
    return reinterpret_cast<const CSteam_Voice_Encoding*>(
               &_CSteam_Voice_Encoding_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CSteam_Voice_Encoding& a, CSteam_Voice_Encoding& b) {
    a.Swap(&b);
  }
  inline void Swap(CSteam_Voice_Encoding* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CSteam_Voice_Encoding* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CSteam_Voice_Encoding* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CSteam_Voice_Encoding>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CSteam_Voice_Encoding& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CSteam_Voice_Encoding& from) {
    CSteam_Voice_Encoding::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CSteam_Voice_Encoding* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "CSteam_Voice_Encoding";
  }
  protected:
  explicit CSteam_Voice_Encoding(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVoiceDataFieldNumber = 1,
  };
  // optional bytes voice_data = 1;
  bool has_voice_data() const;
  void clear_voice_data() ;
  const std::string& voice_data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_voice_data(Arg_&& arg, Args_... args);
  std::string* mutable_voice_data();
  PROTOBUF_NODISCARD std::string* release_voice_data();
  void set_allocated_voice_data(std::string* ptr);

  private:
  const std::string& _internal_voice_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_voice_data(
      const std::string& value);
  std::string* _internal_mutable_voice_data();

  public:
  // @@protoc_insertion_point(class_scope:CSteam_Voice_Encoding)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr voice_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_c_5fpeer2peer_5fnetmessages_2eproto;
};// -------------------------------------------------------------------

class CP2P_Voice final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CP2P_Voice) */ {
 public:
  inline CP2P_Voice() : CP2P_Voice(nullptr) {}
  ~CP2P_Voice() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CP2P_Voice(::google::protobuf::internal::ConstantInitialized);

  CP2P_Voice(const CP2P_Voice& from);
  CP2P_Voice(CP2P_Voice&& from) noexcept
    : CP2P_Voice() {
    *this = ::std::move(from);
  }

  inline CP2P_Voice& operator=(const CP2P_Voice& from) {
    CopyFrom(from);
    return *this;
  }
  inline CP2P_Voice& operator=(CP2P_Voice&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CP2P_Voice& default_instance() {
    return *internal_default_instance();
  }
  static inline const CP2P_Voice* internal_default_instance() {
    return reinterpret_cast<const CP2P_Voice*>(
               &_CP2P_Voice_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CP2P_Voice& a, CP2P_Voice& b) {
    a.Swap(&b);
  }
  inline void Swap(CP2P_Voice* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CP2P_Voice* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CP2P_Voice* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CP2P_Voice>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CP2P_Voice& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CP2P_Voice& from) {
    CP2P_Voice::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CP2P_Voice* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "CP2P_Voice";
  }
  protected:
  explicit CP2P_Voice(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using Handler_Flags = CP2P_Voice_Handler_Flags;
  static constexpr Handler_Flags Played_Audio = CP2P_Voice_Handler_Flags_Played_Audio;
  static inline bool Handler_Flags_IsValid(int value) {
    return CP2P_Voice_Handler_Flags_IsValid(value);
  }
  static constexpr Handler_Flags Handler_Flags_MIN = CP2P_Voice_Handler_Flags_Handler_Flags_MIN;
  static constexpr Handler_Flags Handler_Flags_MAX = CP2P_Voice_Handler_Flags_Handler_Flags_MAX;
  static constexpr int Handler_Flags_ARRAYSIZE = CP2P_Voice_Handler_Flags_Handler_Flags_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* Handler_Flags_descriptor() {
    return CP2P_Voice_Handler_Flags_descriptor();
  }
  template <typename T>
  static inline const std::string& Handler_Flags_Name(T value) {
    return CP2P_Voice_Handler_Flags_Name(value);
  }
  static inline bool Handler_Flags_Parse(absl::string_view name, Handler_Flags* value) {
    return CP2P_Voice_Handler_Flags_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kAudioFieldNumber = 1,
    kBroadcastGroupFieldNumber = 2,
  };
  // optional .CMsgVoiceAudio audio = 1;
  bool has_audio() const;
  void clear_audio() ;
  const ::CMsgVoiceAudio& audio() const;
  PROTOBUF_NODISCARD ::CMsgVoiceAudio* release_audio();
  ::CMsgVoiceAudio* mutable_audio();
  void set_allocated_audio(::CMsgVoiceAudio* value);
  void unsafe_arena_set_allocated_audio(::CMsgVoiceAudio* value);
  ::CMsgVoiceAudio* unsafe_arena_release_audio();

  private:
  const ::CMsgVoiceAudio& _internal_audio() const;
  ::CMsgVoiceAudio* _internal_mutable_audio();

  public:
  // optional uint32 broadcast_group = 2;
  bool has_broadcast_group() const;
  void clear_broadcast_group() ;
  ::uint32_t broadcast_group() const;
  void set_broadcast_group(::uint32_t value);

  private:
  ::uint32_t _internal_broadcast_group() const;
  void _internal_set_broadcast_group(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CP2P_Voice)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 1, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::CMsgVoiceAudio* audio_;
    ::uint32_t broadcast_group_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_c_5fpeer2peer_5fnetmessages_2eproto;
};// -------------------------------------------------------------------

class CP2P_Ping final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CP2P_Ping) */ {
 public:
  inline CP2P_Ping() : CP2P_Ping(nullptr) {}
  ~CP2P_Ping() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CP2P_Ping(::google::protobuf::internal::ConstantInitialized);

  CP2P_Ping(const CP2P_Ping& from);
  CP2P_Ping(CP2P_Ping&& from) noexcept
    : CP2P_Ping() {
    *this = ::std::move(from);
  }

  inline CP2P_Ping& operator=(const CP2P_Ping& from) {
    CopyFrom(from);
    return *this;
  }
  inline CP2P_Ping& operator=(CP2P_Ping&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CP2P_Ping& default_instance() {
    return *internal_default_instance();
  }
  static inline const CP2P_Ping* internal_default_instance() {
    return reinterpret_cast<const CP2P_Ping*>(
               &_CP2P_Ping_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CP2P_Ping& a, CP2P_Ping& b) {
    a.Swap(&b);
  }
  inline void Swap(CP2P_Ping* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CP2P_Ping* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CP2P_Ping* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CP2P_Ping>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CP2P_Ping& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CP2P_Ping& from) {
    CP2P_Ping::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CP2P_Ping* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "CP2P_Ping";
  }
  protected:
  explicit CP2P_Ping(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSendTimeFieldNumber = 1,
    kIsReplyFieldNumber = 2,
  };
  // required uint64 send_time = 1;
  bool has_send_time() const;
  void clear_send_time() ;
  ::uint64_t send_time() const;
  void set_send_time(::uint64_t value);

  private:
  ::uint64_t _internal_send_time() const;
  void _internal_set_send_time(::uint64_t value);

  public:
  // required bool is_reply = 2;
  bool has_is_reply() const;
  void clear_is_reply() ;
  bool is_reply() const;
  void set_is_reply(bool value);

  private:
  bool _internal_is_reply() const;
  void _internal_set_is_reply(bool value);

  public:
  // @@protoc_insertion_point(class_scope:CP2P_Ping)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t send_time_;
    bool is_reply_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_c_5fpeer2peer_5fnetmessages_2eproto;
};// -------------------------------------------------------------------

class CP2P_VRAvatarPosition_COrientation final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CP2P_VRAvatarPosition.COrientation) */ {
 public:
  inline CP2P_VRAvatarPosition_COrientation() : CP2P_VRAvatarPosition_COrientation(nullptr) {}
  ~CP2P_VRAvatarPosition_COrientation() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CP2P_VRAvatarPosition_COrientation(::google::protobuf::internal::ConstantInitialized);

  CP2P_VRAvatarPosition_COrientation(const CP2P_VRAvatarPosition_COrientation& from);
  CP2P_VRAvatarPosition_COrientation(CP2P_VRAvatarPosition_COrientation&& from) noexcept
    : CP2P_VRAvatarPosition_COrientation() {
    *this = ::std::move(from);
  }

  inline CP2P_VRAvatarPosition_COrientation& operator=(const CP2P_VRAvatarPosition_COrientation& from) {
    CopyFrom(from);
    return *this;
  }
  inline CP2P_VRAvatarPosition_COrientation& operator=(CP2P_VRAvatarPosition_COrientation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CP2P_VRAvatarPosition_COrientation& default_instance() {
    return *internal_default_instance();
  }
  static inline const CP2P_VRAvatarPosition_COrientation* internal_default_instance() {
    return reinterpret_cast<const CP2P_VRAvatarPosition_COrientation*>(
               &_CP2P_VRAvatarPosition_COrientation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(CP2P_VRAvatarPosition_COrientation& a, CP2P_VRAvatarPosition_COrientation& b) {
    a.Swap(&b);
  }
  inline void Swap(CP2P_VRAvatarPosition_COrientation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CP2P_VRAvatarPosition_COrientation* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CP2P_VRAvatarPosition_COrientation* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CP2P_VRAvatarPosition_COrientation>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CP2P_VRAvatarPosition_COrientation& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CP2P_VRAvatarPosition_COrientation& from) {
    CP2P_VRAvatarPosition_COrientation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CP2P_VRAvatarPosition_COrientation* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "CP2P_VRAvatarPosition.COrientation";
  }
  protected:
  explicit CP2P_VRAvatarPosition_COrientation(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosFieldNumber = 1,
    kAngFieldNumber = 2,
  };
  // optional .CMsgVector pos = 1;
  bool has_pos() const;
  void clear_pos() ;
  const ::CMsgVector& pos() const;
  PROTOBUF_NODISCARD ::CMsgVector* release_pos();
  ::CMsgVector* mutable_pos();
  void set_allocated_pos(::CMsgVector* value);
  void unsafe_arena_set_allocated_pos(::CMsgVector* value);
  ::CMsgVector* unsafe_arena_release_pos();

  private:
  const ::CMsgVector& _internal_pos() const;
  ::CMsgVector* _internal_mutable_pos();

  public:
  // optional .CMsgQAngle ang = 2;
  bool has_ang() const;
  void clear_ang() ;
  const ::CMsgQAngle& ang() const;
  PROTOBUF_NODISCARD ::CMsgQAngle* release_ang();
  ::CMsgQAngle* mutable_ang();
  void set_allocated_ang(::CMsgQAngle* value);
  void unsafe_arena_set_allocated_ang(::CMsgQAngle* value);
  ::CMsgQAngle* unsafe_arena_release_ang();

  private:
  const ::CMsgQAngle& _internal_ang() const;
  ::CMsgQAngle* _internal_mutable_ang();

  public:
  // @@protoc_insertion_point(class_scope:CP2P_VRAvatarPosition.COrientation)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 2, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::CMsgVector* pos_;
    ::CMsgQAngle* ang_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_c_5fpeer2peer_5fnetmessages_2eproto;
};// -------------------------------------------------------------------

class CP2P_VRAvatarPosition final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CP2P_VRAvatarPosition) */ {
 public:
  inline CP2P_VRAvatarPosition() : CP2P_VRAvatarPosition(nullptr) {}
  ~CP2P_VRAvatarPosition() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CP2P_VRAvatarPosition(::google::protobuf::internal::ConstantInitialized);

  CP2P_VRAvatarPosition(const CP2P_VRAvatarPosition& from);
  CP2P_VRAvatarPosition(CP2P_VRAvatarPosition&& from) noexcept
    : CP2P_VRAvatarPosition() {
    *this = ::std::move(from);
  }

  inline CP2P_VRAvatarPosition& operator=(const CP2P_VRAvatarPosition& from) {
    CopyFrom(from);
    return *this;
  }
  inline CP2P_VRAvatarPosition& operator=(CP2P_VRAvatarPosition&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CP2P_VRAvatarPosition& default_instance() {
    return *internal_default_instance();
  }
  static inline const CP2P_VRAvatarPosition* internal_default_instance() {
    return reinterpret_cast<const CP2P_VRAvatarPosition*>(
               &_CP2P_VRAvatarPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(CP2P_VRAvatarPosition& a, CP2P_VRAvatarPosition& b) {
    a.Swap(&b);
  }
  inline void Swap(CP2P_VRAvatarPosition* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CP2P_VRAvatarPosition* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CP2P_VRAvatarPosition* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CP2P_VRAvatarPosition>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CP2P_VRAvatarPosition& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CP2P_VRAvatarPosition& from) {
    CP2P_VRAvatarPosition::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CP2P_VRAvatarPosition* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "CP2P_VRAvatarPosition";
  }
  protected:
  explicit CP2P_VRAvatarPosition(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CP2P_VRAvatarPosition_COrientation COrientation;

  // accessors -------------------------------------------------------

  enum : int {
    kBodyPartsFieldNumber = 1,
    kHatIdFieldNumber = 2,
    kSceneIdFieldNumber = 3,
    kWorldScaleFieldNumber = 4,
  };
  // repeated .CP2P_VRAvatarPosition.COrientation body_parts = 1;
  int body_parts_size() const;
  private:
  int _internal_body_parts_size() const;

  public:
  void clear_body_parts() ;
  ::CP2P_VRAvatarPosition_COrientation* mutable_body_parts(int index);
  ::google::protobuf::RepeatedPtrField< ::CP2P_VRAvatarPosition_COrientation >*
      mutable_body_parts();
  private:
  const ::google::protobuf::RepeatedPtrField<::CP2P_VRAvatarPosition_COrientation>& _internal_body_parts() const;
  ::google::protobuf::RepeatedPtrField<::CP2P_VRAvatarPosition_COrientation>* _internal_mutable_body_parts();
  public:
  const ::CP2P_VRAvatarPosition_COrientation& body_parts(int index) const;
  ::CP2P_VRAvatarPosition_COrientation* add_body_parts();
  const ::google::protobuf::RepeatedPtrField< ::CP2P_VRAvatarPosition_COrientation >&
      body_parts() const;
  // optional int32 hat_id = 2;
  bool has_hat_id() const;
  void clear_hat_id() ;
  ::int32_t hat_id() const;
  void set_hat_id(::int32_t value);

  private:
  ::int32_t _internal_hat_id() const;
  void _internal_set_hat_id(::int32_t value);

  public:
  // optional int32 scene_id = 3;
  bool has_scene_id() const;
  void clear_scene_id() ;
  ::int32_t scene_id() const;
  void set_scene_id(::int32_t value);

  private:
  ::int32_t _internal_scene_id() const;
  void _internal_set_scene_id(::int32_t value);

  public:
  // optional int32 world_scale = 4;
  bool has_world_scale() const;
  void clear_world_scale() ;
  ::int32_t world_scale() const;
  void set_world_scale(::int32_t value);

  private:
  ::int32_t _internal_world_scale() const;
  void _internal_set_world_scale(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CP2P_VRAvatarPosition)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4, 1, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::CP2P_VRAvatarPosition_COrientation > body_parts_;
    ::int32_t hat_id_;
    ::int32_t scene_id_;
    ::int32_t world_scale_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_c_5fpeer2peer_5fnetmessages_2eproto;
};// -------------------------------------------------------------------

class CP2P_WatchSynchronization final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CP2P_WatchSynchronization) */ {
 public:
  inline CP2P_WatchSynchronization() : CP2P_WatchSynchronization(nullptr) {}
  ~CP2P_WatchSynchronization() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CP2P_WatchSynchronization(::google::protobuf::internal::ConstantInitialized);

  CP2P_WatchSynchronization(const CP2P_WatchSynchronization& from);
  CP2P_WatchSynchronization(CP2P_WatchSynchronization&& from) noexcept
    : CP2P_WatchSynchronization() {
    *this = ::std::move(from);
  }

  inline CP2P_WatchSynchronization& operator=(const CP2P_WatchSynchronization& from) {
    CopyFrom(from);
    return *this;
  }
  inline CP2P_WatchSynchronization& operator=(CP2P_WatchSynchronization&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CP2P_WatchSynchronization& default_instance() {
    return *internal_default_instance();
  }
  static inline const CP2P_WatchSynchronization* internal_default_instance() {
    return reinterpret_cast<const CP2P_WatchSynchronization*>(
               &_CP2P_WatchSynchronization_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(CP2P_WatchSynchronization& a, CP2P_WatchSynchronization& b) {
    a.Swap(&b);
  }
  inline void Swap(CP2P_WatchSynchronization* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CP2P_WatchSynchronization* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CP2P_WatchSynchronization* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CP2P_WatchSynchronization>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CP2P_WatchSynchronization& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CP2P_WatchSynchronization& from) {
    CP2P_WatchSynchronization::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CP2P_WatchSynchronization* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "CP2P_WatchSynchronization";
  }
  protected:
  explicit CP2P_WatchSynchronization(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDemoTickFieldNumber = 1,
    kPausedFieldNumber = 2,
    kDotaSpectatorWatchingBroadcasterFieldNumber = 5,
    kTvListenVoiceIndicesFieldNumber = 3,
    kDotaSpectatorModeFieldNumber = 4,
    kDotaSpectatorHeroIndexFieldNumber = 6,
    kDotaSpectatorAutospeedFieldNumber = 7,
    kDotaReplaySpeedFieldNumber = 8,
  };
  // optional int32 demo_tick = 1;
  bool has_demo_tick() const;
  void clear_demo_tick() ;
  ::int32_t demo_tick() const;
  void set_demo_tick(::int32_t value);

  private:
  ::int32_t _internal_demo_tick() const;
  void _internal_set_demo_tick(::int32_t value);

  public:
  // optional bool paused = 2;
  bool has_paused() const;
  void clear_paused() ;
  bool paused() const;
  void set_paused(bool value);

  private:
  bool _internal_paused() const;
  void _internal_set_paused(bool value);

  public:
  // optional bool dota_spectator_watching_broadcaster = 5;
  bool has_dota_spectator_watching_broadcaster() const;
  void clear_dota_spectator_watching_broadcaster() ;
  bool dota_spectator_watching_broadcaster() const;
  void set_dota_spectator_watching_broadcaster(bool value);

  private:
  bool _internal_dota_spectator_watching_broadcaster() const;
  void _internal_set_dota_spectator_watching_broadcaster(bool value);

  public:
  // optional uint64 tv_listen_voice_indices = 3;
  bool has_tv_listen_voice_indices() const;
  void clear_tv_listen_voice_indices() ;
  ::uint64_t tv_listen_voice_indices() const;
  void set_tv_listen_voice_indices(::uint64_t value);

  private:
  ::uint64_t _internal_tv_listen_voice_indices() const;
  void _internal_set_tv_listen_voice_indices(::uint64_t value);

  public:
  // optional int32 dota_spectator_mode = 4;
  bool has_dota_spectator_mode() const;
  void clear_dota_spectator_mode() ;
  ::int32_t dota_spectator_mode() const;
  void set_dota_spectator_mode(::int32_t value);

  private:
  ::int32_t _internal_dota_spectator_mode() const;
  void _internal_set_dota_spectator_mode(::int32_t value);

  public:
  // optional int32 dota_spectator_hero_index = 6;
  bool has_dota_spectator_hero_index() const;
  void clear_dota_spectator_hero_index() ;
  ::int32_t dota_spectator_hero_index() const;
  void set_dota_spectator_hero_index(::int32_t value);

  private:
  ::int32_t _internal_dota_spectator_hero_index() const;
  void _internal_set_dota_spectator_hero_index(::int32_t value);

  public:
  // optional int32 dota_spectator_autospeed = 7;
  bool has_dota_spectator_autospeed() const;
  void clear_dota_spectator_autospeed() ;
  ::int32_t dota_spectator_autospeed() const;
  void set_dota_spectator_autospeed(::int32_t value);

  private:
  ::int32_t _internal_dota_spectator_autospeed() const;
  void _internal_set_dota_spectator_autospeed(::int32_t value);

  public:
  // optional int32 dota_replay_speed = 8;
  bool has_dota_replay_speed() const;
  void clear_dota_replay_speed() ;
  ::int32_t dota_replay_speed() const;
  void set_dota_replay_speed(::int32_t value);

  private:
  ::int32_t _internal_dota_replay_speed() const;
  void _internal_set_dota_replay_speed(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CP2P_WatchSynchronization)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t demo_tick_;
    bool paused_;
    bool dota_spectator_watching_broadcaster_;
    ::uint64_t tv_listen_voice_indices_;
    ::int32_t dota_spectator_mode_;
    ::int32_t dota_spectator_hero_index_;
    ::int32_t dota_spectator_autospeed_;
    ::int32_t dota_replay_speed_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_c_5fpeer2peer_5fnetmessages_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CP2P_TextMessage

// optional bytes text = 1;
inline bool CP2P_TextMessage::has_text() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CP2P_TextMessage::clear_text() {
  _impl_.text_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CP2P_TextMessage::text() const {
  // @@protoc_insertion_point(field_get:CP2P_TextMessage.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void CP2P_TextMessage::set_text(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.text_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:CP2P_TextMessage.text)
}
inline std::string* CP2P_TextMessage::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:CP2P_TextMessage.text)
  return _s;
}
inline const std::string& CP2P_TextMessage::_internal_text() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.text_.Get();
}
inline void CP2P_TextMessage::_internal_set_text(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* CP2P_TextMessage::_internal_mutable_text() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.text_.Mutable( GetArenaForAllocation());
}
inline std::string* CP2P_TextMessage::release_text() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:CP2P_TextMessage.text)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.text_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.text_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void CP2P_TextMessage::set_allocated_text(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.text_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.text_.IsDefault()) {
          _impl_.text_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CP2P_TextMessage.text)
}

// -------------------------------------------------------------------

// CSteam_Voice_Encoding

// optional bytes voice_data = 1;
inline bool CSteam_Voice_Encoding::has_voice_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CSteam_Voice_Encoding::clear_voice_data() {
  _impl_.voice_data_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CSteam_Voice_Encoding::voice_data() const {
  // @@protoc_insertion_point(field_get:CSteam_Voice_Encoding.voice_data)
  return _internal_voice_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void CSteam_Voice_Encoding::set_voice_data(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.voice_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:CSteam_Voice_Encoding.voice_data)
}
inline std::string* CSteam_Voice_Encoding::mutable_voice_data() {
  std::string* _s = _internal_mutable_voice_data();
  // @@protoc_insertion_point(field_mutable:CSteam_Voice_Encoding.voice_data)
  return _s;
}
inline const std::string& CSteam_Voice_Encoding::_internal_voice_data() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.voice_data_.Get();
}
inline void CSteam_Voice_Encoding::_internal_set_voice_data(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.voice_data_.Set(value, GetArenaForAllocation());
}
inline std::string* CSteam_Voice_Encoding::_internal_mutable_voice_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.voice_data_.Mutable( GetArenaForAllocation());
}
inline std::string* CSteam_Voice_Encoding::release_voice_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:CSteam_Voice_Encoding.voice_data)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.voice_data_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.voice_data_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void CSteam_Voice_Encoding::set_allocated_voice_data(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.voice_data_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.voice_data_.IsDefault()) {
          _impl_.voice_data_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CSteam_Voice_Encoding.voice_data)
}

// -------------------------------------------------------------------

// CP2P_Voice

// optional .CMsgVoiceAudio audio = 1;
inline bool CP2P_Voice::has_audio() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.audio_ != nullptr);
  return value;
}
inline const ::CMsgVoiceAudio& CP2P_Voice::_internal_audio() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::CMsgVoiceAudio* p = _impl_.audio_;
  return p != nullptr ? *p : reinterpret_cast<const ::CMsgVoiceAudio&>(::_CMsgVoiceAudio_default_instance_);
}
inline const ::CMsgVoiceAudio& CP2P_Voice::audio() const {
  // @@protoc_insertion_point(field_get:CP2P_Voice.audio)
  return _internal_audio();
}
inline void CP2P_Voice::unsafe_arena_set_allocated_audio(::CMsgVoiceAudio* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.audio_);
  }
  _impl_.audio_ = reinterpret_cast<::CMsgVoiceAudio*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CP2P_Voice.audio)
}
inline ::CMsgVoiceAudio* CP2P_Voice::release_audio() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::CMsgVoiceAudio* released = _impl_.audio_;
  _impl_.audio_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::CMsgVoiceAudio* CP2P_Voice::unsafe_arena_release_audio() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:CP2P_Voice.audio)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::CMsgVoiceAudio* temp = _impl_.audio_;
  _impl_.audio_ = nullptr;
  return temp;
}
inline ::CMsgVoiceAudio* CP2P_Voice::_internal_mutable_audio() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.audio_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgVoiceAudio>(GetArenaForAllocation());
    _impl_.audio_ = reinterpret_cast<::CMsgVoiceAudio*>(p);
  }
  return _impl_.audio_;
}
inline ::CMsgVoiceAudio* CP2P_Voice::mutable_audio() {
  ::CMsgVoiceAudio* _msg = _internal_mutable_audio();
  // @@protoc_insertion_point(field_mutable:CP2P_Voice.audio)
  return _msg;
}
inline void CP2P_Voice::set_allocated_audio(::CMsgVoiceAudio* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.audio_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.audio_ = reinterpret_cast<::CMsgVoiceAudio*>(value);
  // @@protoc_insertion_point(field_set_allocated:CP2P_Voice.audio)
}

// optional uint32 broadcast_group = 2;
inline bool CP2P_Voice::has_broadcast_group() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void CP2P_Voice::clear_broadcast_group() {
  _impl_.broadcast_group_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t CP2P_Voice::broadcast_group() const {
  // @@protoc_insertion_point(field_get:CP2P_Voice.broadcast_group)
  return _internal_broadcast_group();
}
inline void CP2P_Voice::set_broadcast_group(::uint32_t value) {
  _internal_set_broadcast_group(value);
  // @@protoc_insertion_point(field_set:CP2P_Voice.broadcast_group)
}
inline ::uint32_t CP2P_Voice::_internal_broadcast_group() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.broadcast_group_;
}
inline void CP2P_Voice::_internal_set_broadcast_group(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.broadcast_group_ = value;
}

// -------------------------------------------------------------------

// CP2P_Ping

// required uint64 send_time = 1;
inline bool CP2P_Ping::has_send_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CP2P_Ping::clear_send_time() {
  _impl_.send_time_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t CP2P_Ping::send_time() const {
  // @@protoc_insertion_point(field_get:CP2P_Ping.send_time)
  return _internal_send_time();
}
inline void CP2P_Ping::set_send_time(::uint64_t value) {
  _internal_set_send_time(value);
  // @@protoc_insertion_point(field_set:CP2P_Ping.send_time)
}
inline ::uint64_t CP2P_Ping::_internal_send_time() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.send_time_;
}
inline void CP2P_Ping::_internal_set_send_time(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.send_time_ = value;
}

// required bool is_reply = 2;
inline bool CP2P_Ping::has_is_reply() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void CP2P_Ping::clear_is_reply() {
  _impl_.is_reply_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool CP2P_Ping::is_reply() const {
  // @@protoc_insertion_point(field_get:CP2P_Ping.is_reply)
  return _internal_is_reply();
}
inline void CP2P_Ping::set_is_reply(bool value) {
  _internal_set_is_reply(value);
  // @@protoc_insertion_point(field_set:CP2P_Ping.is_reply)
}
inline bool CP2P_Ping::_internal_is_reply() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.is_reply_;
}
inline void CP2P_Ping::_internal_set_is_reply(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.is_reply_ = value;
}

// -------------------------------------------------------------------

// CP2P_VRAvatarPosition_COrientation

// optional .CMsgVector pos = 1;
inline bool CP2P_VRAvatarPosition_COrientation::has_pos() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.pos_ != nullptr);
  return value;
}
inline const ::CMsgVector& CP2P_VRAvatarPosition_COrientation::_internal_pos() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::CMsgVector* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::CMsgVector&>(::_CMsgVector_default_instance_);
}
inline const ::CMsgVector& CP2P_VRAvatarPosition_COrientation::pos() const {
  // @@protoc_insertion_point(field_get:CP2P_VRAvatarPosition.COrientation.pos)
  return _internal_pos();
}
inline void CP2P_VRAvatarPosition_COrientation::unsafe_arena_set_allocated_pos(::CMsgVector* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = reinterpret_cast<::CMsgVector*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CP2P_VRAvatarPosition.COrientation.pos)
}
inline ::CMsgVector* CP2P_VRAvatarPosition_COrientation::release_pos() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::CMsgVector* released = _impl_.pos_;
  _impl_.pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::CMsgVector* CP2P_VRAvatarPosition_COrientation::unsafe_arena_release_pos() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:CP2P_VRAvatarPosition.COrientation.pos)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::CMsgVector* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::CMsgVector* CP2P_VRAvatarPosition_COrientation::_internal_mutable_pos() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgVector>(GetArenaForAllocation());
    _impl_.pos_ = reinterpret_cast<::CMsgVector*>(p);
  }
  return _impl_.pos_;
}
inline ::CMsgVector* CP2P_VRAvatarPosition_COrientation::mutable_pos() {
  ::CMsgVector* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:CP2P_VRAvatarPosition.COrientation.pos)
  return _msg;
}
inline void CP2P_VRAvatarPosition_COrientation::set_allocated_pos(::CMsgVector* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.pos_ = reinterpret_cast<::CMsgVector*>(value);
  // @@protoc_insertion_point(field_set_allocated:CP2P_VRAvatarPosition.COrientation.pos)
}

// optional .CMsgQAngle ang = 2;
inline bool CP2P_VRAvatarPosition_COrientation::has_ang() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.ang_ != nullptr);
  return value;
}
inline const ::CMsgQAngle& CP2P_VRAvatarPosition_COrientation::_internal_ang() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::CMsgQAngle* p = _impl_.ang_;
  return p != nullptr ? *p : reinterpret_cast<const ::CMsgQAngle&>(::_CMsgQAngle_default_instance_);
}
inline const ::CMsgQAngle& CP2P_VRAvatarPosition_COrientation::ang() const {
  // @@protoc_insertion_point(field_get:CP2P_VRAvatarPosition.COrientation.ang)
  return _internal_ang();
}
inline void CP2P_VRAvatarPosition_COrientation::unsafe_arena_set_allocated_ang(::CMsgQAngle* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ang_);
  }
  _impl_.ang_ = reinterpret_cast<::CMsgQAngle*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CP2P_VRAvatarPosition.COrientation.ang)
}
inline ::CMsgQAngle* CP2P_VRAvatarPosition_COrientation::release_ang() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::CMsgQAngle* released = _impl_.ang_;
  _impl_.ang_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::CMsgQAngle* CP2P_VRAvatarPosition_COrientation::unsafe_arena_release_ang() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:CP2P_VRAvatarPosition.COrientation.ang)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::CMsgQAngle* temp = _impl_.ang_;
  _impl_.ang_ = nullptr;
  return temp;
}
inline ::CMsgQAngle* CP2P_VRAvatarPosition_COrientation::_internal_mutable_ang() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.ang_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgQAngle>(GetArenaForAllocation());
    _impl_.ang_ = reinterpret_cast<::CMsgQAngle*>(p);
  }
  return _impl_.ang_;
}
inline ::CMsgQAngle* CP2P_VRAvatarPosition_COrientation::mutable_ang() {
  ::CMsgQAngle* _msg = _internal_mutable_ang();
  // @@protoc_insertion_point(field_mutable:CP2P_VRAvatarPosition.COrientation.ang)
  return _msg;
}
inline void CP2P_VRAvatarPosition_COrientation::set_allocated_ang(::CMsgQAngle* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ang_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.ang_ = reinterpret_cast<::CMsgQAngle*>(value);
  // @@protoc_insertion_point(field_set_allocated:CP2P_VRAvatarPosition.COrientation.ang)
}

// -------------------------------------------------------------------

// CP2P_VRAvatarPosition

// repeated .CP2P_VRAvatarPosition.COrientation body_parts = 1;
inline int CP2P_VRAvatarPosition::_internal_body_parts_size() const {
  return _internal_body_parts().size();
}
inline int CP2P_VRAvatarPosition::body_parts_size() const {
  return _internal_body_parts_size();
}
inline void CP2P_VRAvatarPosition::clear_body_parts() {
  _internal_mutable_body_parts()->Clear();
}
inline ::CP2P_VRAvatarPosition_COrientation* CP2P_VRAvatarPosition::mutable_body_parts(int index) {
  // @@protoc_insertion_point(field_mutable:CP2P_VRAvatarPosition.body_parts)
  return _internal_mutable_body_parts()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::CP2P_VRAvatarPosition_COrientation >*
CP2P_VRAvatarPosition::mutable_body_parts() {
  // @@protoc_insertion_point(field_mutable_list:CP2P_VRAvatarPosition.body_parts)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_body_parts();
}
inline const ::CP2P_VRAvatarPosition_COrientation& CP2P_VRAvatarPosition::body_parts(int index) const {
  // @@protoc_insertion_point(field_get:CP2P_VRAvatarPosition.body_parts)
    return _internal_body_parts().Get(index);
}
inline ::CP2P_VRAvatarPosition_COrientation* CP2P_VRAvatarPosition::add_body_parts() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::CP2P_VRAvatarPosition_COrientation* _add = _internal_mutable_body_parts()->Add();
  // @@protoc_insertion_point(field_add:CP2P_VRAvatarPosition.body_parts)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::CP2P_VRAvatarPosition_COrientation >&
CP2P_VRAvatarPosition::body_parts() const {
  // @@protoc_insertion_point(field_list:CP2P_VRAvatarPosition.body_parts)
  return _internal_body_parts();
}
inline const ::google::protobuf::RepeatedPtrField<::CP2P_VRAvatarPosition_COrientation>&
CP2P_VRAvatarPosition::_internal_body_parts() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.body_parts_;
}
inline ::google::protobuf::RepeatedPtrField<::CP2P_VRAvatarPosition_COrientation>*
CP2P_VRAvatarPosition::_internal_mutable_body_parts() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.body_parts_;
}

// optional int32 hat_id = 2;
inline bool CP2P_VRAvatarPosition::has_hat_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CP2P_VRAvatarPosition::clear_hat_id() {
  _impl_.hat_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t CP2P_VRAvatarPosition::hat_id() const {
  // @@protoc_insertion_point(field_get:CP2P_VRAvatarPosition.hat_id)
  return _internal_hat_id();
}
inline void CP2P_VRAvatarPosition::set_hat_id(::int32_t value) {
  _internal_set_hat_id(value);
  // @@protoc_insertion_point(field_set:CP2P_VRAvatarPosition.hat_id)
}
inline ::int32_t CP2P_VRAvatarPosition::_internal_hat_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.hat_id_;
}
inline void CP2P_VRAvatarPosition::_internal_set_hat_id(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.hat_id_ = value;
}

// optional int32 scene_id = 3;
inline bool CP2P_VRAvatarPosition::has_scene_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void CP2P_VRAvatarPosition::clear_scene_id() {
  _impl_.scene_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t CP2P_VRAvatarPosition::scene_id() const {
  // @@protoc_insertion_point(field_get:CP2P_VRAvatarPosition.scene_id)
  return _internal_scene_id();
}
inline void CP2P_VRAvatarPosition::set_scene_id(::int32_t value) {
  _internal_set_scene_id(value);
  // @@protoc_insertion_point(field_set:CP2P_VRAvatarPosition.scene_id)
}
inline ::int32_t CP2P_VRAvatarPosition::_internal_scene_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.scene_id_;
}
inline void CP2P_VRAvatarPosition::_internal_set_scene_id(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.scene_id_ = value;
}

// optional int32 world_scale = 4;
inline bool CP2P_VRAvatarPosition::has_world_scale() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void CP2P_VRAvatarPosition::clear_world_scale() {
  _impl_.world_scale_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t CP2P_VRAvatarPosition::world_scale() const {
  // @@protoc_insertion_point(field_get:CP2P_VRAvatarPosition.world_scale)
  return _internal_world_scale();
}
inline void CP2P_VRAvatarPosition::set_world_scale(::int32_t value) {
  _internal_set_world_scale(value);
  // @@protoc_insertion_point(field_set:CP2P_VRAvatarPosition.world_scale)
}
inline ::int32_t CP2P_VRAvatarPosition::_internal_world_scale() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.world_scale_;
}
inline void CP2P_VRAvatarPosition::_internal_set_world_scale(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.world_scale_ = value;
}

// -------------------------------------------------------------------

// CP2P_WatchSynchronization

// optional int32 demo_tick = 1;
inline bool CP2P_WatchSynchronization::has_demo_tick() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CP2P_WatchSynchronization::clear_demo_tick() {
  _impl_.demo_tick_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t CP2P_WatchSynchronization::demo_tick() const {
  // @@protoc_insertion_point(field_get:CP2P_WatchSynchronization.demo_tick)
  return _internal_demo_tick();
}
inline void CP2P_WatchSynchronization::set_demo_tick(::int32_t value) {
  _internal_set_demo_tick(value);
  // @@protoc_insertion_point(field_set:CP2P_WatchSynchronization.demo_tick)
}
inline ::int32_t CP2P_WatchSynchronization::_internal_demo_tick() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.demo_tick_;
}
inline void CP2P_WatchSynchronization::_internal_set_demo_tick(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.demo_tick_ = value;
}

// optional bool paused = 2;
inline bool CP2P_WatchSynchronization::has_paused() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void CP2P_WatchSynchronization::clear_paused() {
  _impl_.paused_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool CP2P_WatchSynchronization::paused() const {
  // @@protoc_insertion_point(field_get:CP2P_WatchSynchronization.paused)
  return _internal_paused();
}
inline void CP2P_WatchSynchronization::set_paused(bool value) {
  _internal_set_paused(value);
  // @@protoc_insertion_point(field_set:CP2P_WatchSynchronization.paused)
}
inline bool CP2P_WatchSynchronization::_internal_paused() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.paused_;
}
inline void CP2P_WatchSynchronization::_internal_set_paused(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.paused_ = value;
}

// optional uint64 tv_listen_voice_indices = 3;
inline bool CP2P_WatchSynchronization::has_tv_listen_voice_indices() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void CP2P_WatchSynchronization::clear_tv_listen_voice_indices() {
  _impl_.tv_listen_voice_indices_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::uint64_t CP2P_WatchSynchronization::tv_listen_voice_indices() const {
  // @@protoc_insertion_point(field_get:CP2P_WatchSynchronization.tv_listen_voice_indices)
  return _internal_tv_listen_voice_indices();
}
inline void CP2P_WatchSynchronization::set_tv_listen_voice_indices(::uint64_t value) {
  _internal_set_tv_listen_voice_indices(value);
  // @@protoc_insertion_point(field_set:CP2P_WatchSynchronization.tv_listen_voice_indices)
}
inline ::uint64_t CP2P_WatchSynchronization::_internal_tv_listen_voice_indices() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tv_listen_voice_indices_;
}
inline void CP2P_WatchSynchronization::_internal_set_tv_listen_voice_indices(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.tv_listen_voice_indices_ = value;
}

// optional int32 dota_spectator_mode = 4;
inline bool CP2P_WatchSynchronization::has_dota_spectator_mode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void CP2P_WatchSynchronization::clear_dota_spectator_mode() {
  _impl_.dota_spectator_mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t CP2P_WatchSynchronization::dota_spectator_mode() const {
  // @@protoc_insertion_point(field_get:CP2P_WatchSynchronization.dota_spectator_mode)
  return _internal_dota_spectator_mode();
}
inline void CP2P_WatchSynchronization::set_dota_spectator_mode(::int32_t value) {
  _internal_set_dota_spectator_mode(value);
  // @@protoc_insertion_point(field_set:CP2P_WatchSynchronization.dota_spectator_mode)
}
inline ::int32_t CP2P_WatchSynchronization::_internal_dota_spectator_mode() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.dota_spectator_mode_;
}
inline void CP2P_WatchSynchronization::_internal_set_dota_spectator_mode(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.dota_spectator_mode_ = value;
}

// optional bool dota_spectator_watching_broadcaster = 5;
inline bool CP2P_WatchSynchronization::has_dota_spectator_watching_broadcaster() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void CP2P_WatchSynchronization::clear_dota_spectator_watching_broadcaster() {
  _impl_.dota_spectator_watching_broadcaster_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool CP2P_WatchSynchronization::dota_spectator_watching_broadcaster() const {
  // @@protoc_insertion_point(field_get:CP2P_WatchSynchronization.dota_spectator_watching_broadcaster)
  return _internal_dota_spectator_watching_broadcaster();
}
inline void CP2P_WatchSynchronization::set_dota_spectator_watching_broadcaster(bool value) {
  _internal_set_dota_spectator_watching_broadcaster(value);
  // @@protoc_insertion_point(field_set:CP2P_WatchSynchronization.dota_spectator_watching_broadcaster)
}
inline bool CP2P_WatchSynchronization::_internal_dota_spectator_watching_broadcaster() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.dota_spectator_watching_broadcaster_;
}
inline void CP2P_WatchSynchronization::_internal_set_dota_spectator_watching_broadcaster(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.dota_spectator_watching_broadcaster_ = value;
}

// optional int32 dota_spectator_hero_index = 6;
inline bool CP2P_WatchSynchronization::has_dota_spectator_hero_index() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void CP2P_WatchSynchronization::clear_dota_spectator_hero_index() {
  _impl_.dota_spectator_hero_index_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t CP2P_WatchSynchronization::dota_spectator_hero_index() const {
  // @@protoc_insertion_point(field_get:CP2P_WatchSynchronization.dota_spectator_hero_index)
  return _internal_dota_spectator_hero_index();
}
inline void CP2P_WatchSynchronization::set_dota_spectator_hero_index(::int32_t value) {
  _internal_set_dota_spectator_hero_index(value);
  // @@protoc_insertion_point(field_set:CP2P_WatchSynchronization.dota_spectator_hero_index)
}
inline ::int32_t CP2P_WatchSynchronization::_internal_dota_spectator_hero_index() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.dota_spectator_hero_index_;
}
inline void CP2P_WatchSynchronization::_internal_set_dota_spectator_hero_index(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.dota_spectator_hero_index_ = value;
}

// optional int32 dota_spectator_autospeed = 7;
inline bool CP2P_WatchSynchronization::has_dota_spectator_autospeed() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void CP2P_WatchSynchronization::clear_dota_spectator_autospeed() {
  _impl_.dota_spectator_autospeed_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t CP2P_WatchSynchronization::dota_spectator_autospeed() const {
  // @@protoc_insertion_point(field_get:CP2P_WatchSynchronization.dota_spectator_autospeed)
  return _internal_dota_spectator_autospeed();
}
inline void CP2P_WatchSynchronization::set_dota_spectator_autospeed(::int32_t value) {
  _internal_set_dota_spectator_autospeed(value);
  // @@protoc_insertion_point(field_set:CP2P_WatchSynchronization.dota_spectator_autospeed)
}
inline ::int32_t CP2P_WatchSynchronization::_internal_dota_spectator_autospeed() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.dota_spectator_autospeed_;
}
inline void CP2P_WatchSynchronization::_internal_set_dota_spectator_autospeed(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.dota_spectator_autospeed_ = value;
}

// optional int32 dota_replay_speed = 8;
inline bool CP2P_WatchSynchronization::has_dota_replay_speed() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void CP2P_WatchSynchronization::clear_dota_replay_speed() {
  _impl_.dota_replay_speed_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t CP2P_WatchSynchronization::dota_replay_speed() const {
  // @@protoc_insertion_point(field_get:CP2P_WatchSynchronization.dota_replay_speed)
  return _internal_dota_replay_speed();
}
inline void CP2P_WatchSynchronization::set_dota_replay_speed(::int32_t value) {
  _internal_set_dota_replay_speed(value);
  // @@protoc_insertion_point(field_set:CP2P_WatchSynchronization.dota_replay_speed)
}
inline ::int32_t CP2P_WatchSynchronization::_internal_dota_replay_speed() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.dota_replay_speed_;
}
inline void CP2P_WatchSynchronization::_internal_set_dota_replay_speed(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.dota_replay_speed_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::CP2P_Voice_Handler_Flags> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::CP2P_Voice_Handler_Flags>() {
  return ::CP2P_Voice_Handler_Flags_descriptor();
}
template <>
struct is_proto_enum<::P2P_Messages> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::P2P_Messages>() {
  return ::P2P_Messages_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_c_5fpeer2peer_5fnetmessages_2eproto_2epb_2eh
