// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usercmd.proto

#include "usercmd.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
        template <typename>
PROTOBUF_CONSTEXPR CInButtonStatePB::CInButtonStatePB(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.buttonstate1_)*/ ::uint64_t{0u},
      /*decltype(_impl_.buttonstate2_)*/ ::uint64_t{0u},
      /*decltype(_impl_.buttonstate3_)*/ ::uint64_t{0u},
    } {}
struct CInButtonStatePBDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CInButtonStatePBDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CInButtonStatePBDefaultTypeInternal() {}
  union {
    CInButtonStatePB _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CInButtonStatePBDefaultTypeInternal _CInButtonStatePB_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR CSubtickMoveStep::CSubtickMoveStep(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.button_)*/ ::uint64_t{0u},
      /*decltype(_impl_.pressed_)*/ false,
      /*decltype(_impl_.when_)*/ 0,
    } {}
struct CSubtickMoveStepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CSubtickMoveStepDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CSubtickMoveStepDefaultTypeInternal() {}
  union {
    CSubtickMoveStep _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CSubtickMoveStepDefaultTypeInternal _CSubtickMoveStep_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR CBaseUserCmdPB::CBaseUserCmdPB(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.subtick_moves_)*/ {},
      /*decltype(_impl_.move_crc_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.buttons_pb_)*/ nullptr,
      /*decltype(_impl_.viewangles_)*/ nullptr,
      /*decltype(_impl_.command_number_)*/ 0,
      /*decltype(_impl_.tick_count_)*/ 0,
      /*decltype(_impl_.forwardmove_)*/ 0,
      /*decltype(_impl_.leftmove_)*/ 0,
      /*decltype(_impl_.upmove_)*/ 0,
      /*decltype(_impl_.impulse_)*/ 0,
      /*decltype(_impl_.weaponselect_)*/ 0,
      /*decltype(_impl_.random_seed_)*/ 0,
      /*decltype(_impl_.mousedx_)*/ 0,
      /*decltype(_impl_.mousedy_)*/ 0,
      /*decltype(_impl_.hasbeenpredicted_)*/ false,
      /*decltype(_impl_.consumed_server_angle_changes_)*/ 0u,
      /*decltype(_impl_.cmd_flags_)*/ 0,
      /*decltype(_impl_.pawn_entity_handle_)*/ 16777215u,
    } {}
struct CBaseUserCmdPBDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CBaseUserCmdPBDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CBaseUserCmdPBDefaultTypeInternal() {}
  union {
    CBaseUserCmdPB _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CBaseUserCmdPBDefaultTypeInternal _CBaseUserCmdPB_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR CUserCmdBasePB::CUserCmdBasePB(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.base_)*/ nullptr,
    } {}
struct CUserCmdBasePBDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CUserCmdBasePBDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CUserCmdBasePBDefaultTypeInternal() {}
  union {
    CUserCmdBasePB _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CUserCmdBasePBDefaultTypeInternal _CUserCmdBasePB_default_instance_;
static ::_pb::Metadata file_level_metadata_usercmd_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_usercmd_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_usercmd_2eproto = nullptr;
const ::uint32_t TableStruct_usercmd_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _impl_.buttonstate1_),
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _impl_.buttonstate2_),
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _impl_.buttonstate3_),
    0,
    1,
    2,
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.button_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.pressed_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.when_),
    0,
    1,
    2,
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.command_number_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.tick_count_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.buttons_pb_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.viewangles_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.forwardmove_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.leftmove_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.upmove_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.impulse_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.weaponselect_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.random_seed_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.mousedx_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.mousedy_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.hasbeenpredicted_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.pawn_entity_handle_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.subtick_moves_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.move_crc_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.consumed_server_angle_changes_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.cmd_flags_),
    3,
    4,
    1,
    2,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    16,
    ~0u,
    0,
    14,
    15,
    PROTOBUF_FIELD_OFFSET(::CUserCmdBasePB, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CUserCmdBasePB, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CUserCmdBasePB, _impl_.base_),
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::CInButtonStatePB)},
        {14, 25, -1, sizeof(::CSubtickMoveStep)},
        {28, 54, -1, sizeof(::CBaseUserCmdPB)},
        {72, 81, -1, sizeof(::CUserCmdBasePB)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_CInButtonStatePB_default_instance_._instance,
    &::_CSubtickMoveStep_default_instance_._instance,
    &::_CBaseUserCmdPB_default_instance_._instance,
    &::_CUserCmdBasePB_default_instance_._instance,
};
const char descriptor_table_protodef_usercmd_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rusercmd.proto\032\026networkbasetypes.proto\""
    "T\n\020CInButtonStatePB\022\024\n\014buttonstate1\030\001 \001("
    "\004\022\024\n\014buttonstate2\030\002 \001(\004\022\024\n\014buttonstate3\030"
    "\003 \001(\004\"A\n\020CSubtickMoveStep\022\016\n\006button\030\001 \001("
    "\004\022\017\n\007pressed\030\002 \001(\010\022\014\n\004when\030\003 \001(\002\"\317\003\n\016CBa"
    "seUserCmdPB\022\026\n\016command_number\030\001 \001(\005\022\022\n\nt"
    "ick_count\030\002 \001(\005\022%\n\nbuttons_pb\030\003 \001(\0132\021.CI"
    "nButtonStatePB\022\037\n\nviewangles\030\004 \001(\0132\013.CMs"
    "gQAngle\022\023\n\013forwardmove\030\005 \001(\002\022\020\n\010leftmove"
    "\030\006 \001(\002\022\016\n\006upmove\030\007 \001(\002\022\017\n\007impulse\030\010 \001(\005\022"
    "\024\n\014weaponselect\030\t \001(\005\022\023\n\013random_seed\030\n \001"
    "(\005\022\017\n\007mousedx\030\013 \001(\005\022\017\n\007mousedy\030\014 \001(\005\022\030\n\020"
    "hasbeenpredicted\030\r \001(\010\022$\n\022pawn_entity_ha"
    "ndle\030\016 \001(\r:\01016777215\022(\n\rsubtick_moves\030\022 "
    "\003(\0132\021.CSubtickMoveStep\022\020\n\010move_crc\030\023 \001(\014"
    "\022%\n\035consumed_server_angle_changes\030\024 \001(\r\022"
    "\021\n\tcmd_flags\030\025 \001(\005\"/\n\016CUserCmdBasePB\022\035\n\004"
    "base\030\001 \001(\0132\017.CBaseUserCmdPB"
};
static const ::_pbi::DescriptorTable* const descriptor_table_usercmd_2eproto_deps[1] =
    {
        &::descriptor_table_networkbasetypes_2eproto,
};
static ::absl::once_flag descriptor_table_usercmd_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_usercmd_2eproto = {
    false,
    false,
    707,
    descriptor_table_protodef_usercmd_2eproto,
    "usercmd.proto",
    &descriptor_table_usercmd_2eproto_once,
    descriptor_table_usercmd_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_usercmd_2eproto::offsets,
    file_level_metadata_usercmd_2eproto,
    file_level_enum_descriptors_usercmd_2eproto,
    file_level_service_descriptors_usercmd_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_usercmd_2eproto_getter() {
  return &descriptor_table_usercmd_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_usercmd_2eproto(&descriptor_table_usercmd_2eproto);
// ===================================================================

class CInButtonStatePB::_Internal {
 public:
  using HasBits = decltype(std::declval<CInButtonStatePB>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_._has_bits_);
  static void set_has_buttonstate1(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_buttonstate2(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_buttonstate3(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

CInButtonStatePB::CInButtonStatePB(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CInButtonStatePB)
}
CInButtonStatePB::CInButtonStatePB(const CInButtonStatePB& from)
    : ::google::protobuf::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CInButtonStatePB)
}
inline void CInButtonStatePB::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.buttonstate1_){::uint64_t{0u}},
      decltype(_impl_.buttonstate2_){::uint64_t{0u}},
      decltype(_impl_.buttonstate3_){::uint64_t{0u}},
  };
}
CInButtonStatePB::~CInButtonStatePB() {
  // @@protoc_insertion_point(destructor:CInButtonStatePB)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CInButtonStatePB::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void CInButtonStatePB::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CInButtonStatePB::Clear() {
// @@protoc_insertion_point(message_clear_start:CInButtonStatePB)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.buttonstate1_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.buttonstate3_) -
        reinterpret_cast<char*>(&_impl_.buttonstate1_)) + sizeof(_impl_.buttonstate3_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CInButtonStatePB::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> CInButtonStatePB::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CInButtonStatePB_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint64 buttonstate1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CInButtonStatePB, _impl_.buttonstate1_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate1_)}},
    // optional uint64 buttonstate2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CInButtonStatePB, _impl_.buttonstate2_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate2_)}},
    // optional uint64 buttonstate3 = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CInButtonStatePB, _impl_.buttonstate3_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate3_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 buttonstate1 = 1;
    {PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate1_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 buttonstate2 = 2;
    {PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate2_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 buttonstate3 = 3;
    {PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate3_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CInButtonStatePB::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CInButtonStatePB)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint64 buttonstate1 = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_buttonstate1(), target);
  }

  // optional uint64 buttonstate2 = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_buttonstate2(), target);
  }

  // optional uint64 buttonstate3 = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_buttonstate3(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CInButtonStatePB)
  return target;
}

::size_t CInButtonStatePB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CInButtonStatePB)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional uint64 buttonstate1 = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_buttonstate1());
    }

    // optional uint64 buttonstate2 = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_buttonstate2());
    }

    // optional uint64 buttonstate3 = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_buttonstate3());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CInButtonStatePB::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    CInButtonStatePB::MergeImpl
};
const ::google::protobuf::Message::ClassData*CInButtonStatePB::GetClassData() const { return &_class_data_; }


void CInButtonStatePB::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CInButtonStatePB*>(&to_msg);
  auto& from = static_cast<const CInButtonStatePB&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CInButtonStatePB)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.buttonstate1_ = from._impl_.buttonstate1_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.buttonstate2_ = from._impl_.buttonstate2_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.buttonstate3_ = from._impl_.buttonstate3_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CInButtonStatePB::CopyFrom(const CInButtonStatePB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CInButtonStatePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CInButtonStatePB::IsInitialized() const {
  return true;
}

void CInButtonStatePB::InternalSwap(CInButtonStatePB* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate3_)
      + sizeof(CInButtonStatePB::_impl_.buttonstate3_)
      - PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate1_)>(
          reinterpret_cast<char*>(&_impl_.buttonstate1_),
          reinterpret_cast<char*>(&other->_impl_.buttonstate1_));
}

::google::protobuf::Metadata CInButtonStatePB::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_usercmd_2eproto_getter, &descriptor_table_usercmd_2eproto_once,
      file_level_metadata_usercmd_2eproto[0]);
}
// ===================================================================

class CSubtickMoveStep::_Internal {
 public:
  using HasBits = decltype(std::declval<CSubtickMoveStep>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_._has_bits_);
  static void set_has_button(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_pressed(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_when(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

CSubtickMoveStep::CSubtickMoveStep(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CSubtickMoveStep)
}
CSubtickMoveStep::CSubtickMoveStep(const CSubtickMoveStep& from)
    : ::google::protobuf::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CSubtickMoveStep)
}
inline void CSubtickMoveStep::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.button_){::uint64_t{0u}},
      decltype(_impl_.pressed_){false},
      decltype(_impl_.when_){0},
  };
}
CSubtickMoveStep::~CSubtickMoveStep() {
  // @@protoc_insertion_point(destructor:CSubtickMoveStep)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CSubtickMoveStep::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void CSubtickMoveStep::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CSubtickMoveStep::Clear() {
// @@protoc_insertion_point(message_clear_start:CSubtickMoveStep)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.button_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.when_) -
        reinterpret_cast<char*>(&_impl_.button_)) + sizeof(_impl_.when_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CSubtickMoveStep::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> CSubtickMoveStep::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CSubtickMoveStep_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint64 button = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CSubtickMoveStep, _impl_.button_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.button_)}},
    // optional bool pressed = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CSubtickMoveStep, _impl_.pressed_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.pressed_)}},
    // optional float when = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.when_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 button = 1;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.button_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional bool pressed = 2;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.pressed_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional float when = 3;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.when_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CSubtickMoveStep::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSubtickMoveStep)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint64 button = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_button(), target);
  }

  // optional bool pressed = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_pressed(), target);
  }

  // optional float when = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_when(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CSubtickMoveStep)
  return target;
}

::size_t CSubtickMoveStep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CSubtickMoveStep)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional uint64 button = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_button());
    }

    // optional bool pressed = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 2;
    }

    // optional float when = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 5;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CSubtickMoveStep::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    CSubtickMoveStep::MergeImpl
};
const ::google::protobuf::Message::ClassData*CSubtickMoveStep::GetClassData() const { return &_class_data_; }


void CSubtickMoveStep::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CSubtickMoveStep*>(&to_msg);
  auto& from = static_cast<const CSubtickMoveStep&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CSubtickMoveStep)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.button_ = from._impl_.button_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.pressed_ = from._impl_.pressed_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.when_ = from._impl_.when_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CSubtickMoveStep::CopyFrom(const CSubtickMoveStep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSubtickMoveStep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CSubtickMoveStep::IsInitialized() const {
  return true;
}

void CSubtickMoveStep::InternalSwap(CSubtickMoveStep* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.when_)
      + sizeof(CSubtickMoveStep::_impl_.when_)
      - PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.button_)>(
          reinterpret_cast<char*>(&_impl_.button_),
          reinterpret_cast<char*>(&other->_impl_.button_));
}

::google::protobuf::Metadata CSubtickMoveStep::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_usercmd_2eproto_getter, &descriptor_table_usercmd_2eproto_once,
      file_level_metadata_usercmd_2eproto[1]);
}
// ===================================================================

class CBaseUserCmdPB::_Internal {
 public:
  using HasBits = decltype(std::declval<CBaseUserCmdPB>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_._has_bits_);
  static void set_has_command_number(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_tick_count(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::CInButtonStatePB& buttons_pb(const CBaseUserCmdPB* msg);
  static void set_has_buttons_pb(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::CMsgQAngle& viewangles(const CBaseUserCmdPB* msg);
  static void set_has_viewangles(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_forwardmove(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_leftmove(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_upmove(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_impulse(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_weaponselect(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_random_seed(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_mousedx(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_mousedy(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static void set_has_hasbeenpredicted(HasBits* has_bits) {
    (*has_bits)[0] |= 8192u;
  }
  static void set_has_pawn_entity_handle(HasBits* has_bits) {
    (*has_bits)[0] |= 65536u;
  }
  static void set_has_move_crc(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_consumed_server_angle_changes(HasBits* has_bits) {
    (*has_bits)[0] |= 16384u;
  }
  static void set_has_cmd_flags(HasBits* has_bits) {
    (*has_bits)[0] |= 32768u;
  }
};

const ::CInButtonStatePB& CBaseUserCmdPB::_Internal::buttons_pb(const CBaseUserCmdPB* msg) {
  return *msg->_impl_.buttons_pb_;
}
const ::CMsgQAngle& CBaseUserCmdPB::_Internal::viewangles(const CBaseUserCmdPB* msg) {
  return *msg->_impl_.viewangles_;
}
void CBaseUserCmdPB::clear_viewangles() {
  if (_impl_.viewangles_ != nullptr) _impl_.viewangles_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
CBaseUserCmdPB::CBaseUserCmdPB(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CBaseUserCmdPB)
}
CBaseUserCmdPB::CBaseUserCmdPB(const CBaseUserCmdPB& from) : ::google::protobuf::Message() {
  CBaseUserCmdPB* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.subtick_moves_){from._impl_.subtick_moves_},
      decltype(_impl_.move_crc_){},
      decltype(_impl_.buttons_pb_){nullptr},
      decltype(_impl_.viewangles_){nullptr},
      decltype(_impl_.command_number_){},
      decltype(_impl_.tick_count_){},
      decltype(_impl_.forwardmove_){},
      decltype(_impl_.leftmove_){},
      decltype(_impl_.upmove_){},
      decltype(_impl_.impulse_){},
      decltype(_impl_.weaponselect_){},
      decltype(_impl_.random_seed_){},
      decltype(_impl_.mousedx_){},
      decltype(_impl_.mousedy_){},
      decltype(_impl_.hasbeenpredicted_){},
      decltype(_impl_.consumed_server_angle_changes_){},
      decltype(_impl_.cmd_flags_){},
      decltype(_impl_.pawn_entity_handle_){},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.move_crc_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.move_crc_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.move_crc_.Set(from._internal_move_crc(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.buttons_pb_ = new ::CInButtonStatePB(*from._impl_.buttons_pb_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000004u) != 0) {
    _this->_impl_.viewangles_ = new ::CMsgQAngle(*from._impl_.viewangles_);
  }
  ::memcpy(&_impl_.command_number_, &from._impl_.command_number_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.pawn_entity_handle_) -
    reinterpret_cast<char*>(&_impl_.command_number_)) + sizeof(_impl_.pawn_entity_handle_));

  // @@protoc_insertion_point(copy_constructor:CBaseUserCmdPB)
}
inline void CBaseUserCmdPB::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.subtick_moves_){arena},
      decltype(_impl_.move_crc_){},
      decltype(_impl_.buttons_pb_){nullptr},
      decltype(_impl_.viewangles_){nullptr},
      decltype(_impl_.command_number_){0},
      decltype(_impl_.tick_count_){0},
      decltype(_impl_.forwardmove_){0},
      decltype(_impl_.leftmove_){0},
      decltype(_impl_.upmove_){0},
      decltype(_impl_.impulse_){0},
      decltype(_impl_.weaponselect_){0},
      decltype(_impl_.random_seed_){0},
      decltype(_impl_.mousedx_){0},
      decltype(_impl_.mousedy_){0},
      decltype(_impl_.hasbeenpredicted_){false},
      decltype(_impl_.consumed_server_angle_changes_){0u},
      decltype(_impl_.cmd_flags_){0},
      decltype(_impl_.pawn_entity_handle_){16777215u},
  };
  _impl_.move_crc_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.move_crc_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
CBaseUserCmdPB::~CBaseUserCmdPB() {
  // @@protoc_insertion_point(destructor:CBaseUserCmdPB)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CBaseUserCmdPB::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.subtick_moves_.~RepeatedPtrField();
  _impl_.move_crc_.Destroy();
  if (this != internal_default_instance()) delete _impl_.buttons_pb_;
  if (this != internal_default_instance()) delete _impl_.viewangles_;
}
void CBaseUserCmdPB::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CBaseUserCmdPB::Clear() {
// @@protoc_insertion_point(message_clear_start:CBaseUserCmdPB)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_subtick_moves()->Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.move_crc_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.buttons_pb_ != nullptr);
      _impl_.buttons_pb_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.viewangles_ != nullptr);
      _impl_.viewangles_->Clear();
    }
  }
  if (cached_has_bits & 0x000000f8u) {
    ::memset(&_impl_.command_number_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.upmove_) -
        reinterpret_cast<char*>(&_impl_.command_number_)) + sizeof(_impl_.upmove_));
  }
  if (cached_has_bits & 0x0000ff00u) {
    ::memset(&_impl_.impulse_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.cmd_flags_) -
        reinterpret_cast<char*>(&_impl_.impulse_)) + sizeof(_impl_.cmd_flags_));
  }
  _impl_.pawn_entity_handle_ = 16777215u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CBaseUserCmdPB::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 18, 3, 0, 2> CBaseUserCmdPB::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_._has_bits_),
    0, // no _extensions_
    21, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4292984832,  // skipmap
    offsetof(decltype(_table_), field_entries),
    18,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CBaseUserCmdPB_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 command_number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.command_number_), 3>(),
     {8, 3, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.command_number_)}},
    // optional int32 tick_count = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.tick_count_), 4>(),
     {16, 4, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.tick_count_)}},
    // optional .CInButtonStatePB buttons_pb = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.buttons_pb_)}},
    // optional .CMsgQAngle viewangles = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 1, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.viewangles_)}},
    // optional float forwardmove = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 5, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.forwardmove_)}},
    // optional float leftmove = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 6, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.leftmove_)}},
    // optional float upmove = 7;
    {::_pbi::TcParser::FastF32S1,
     {61, 7, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.upmove_)}},
    // optional int32 impulse = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.impulse_), 8>(),
     {64, 8, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.impulse_)}},
    // optional int32 weaponselect = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.weaponselect_), 9>(),
     {72, 9, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.weaponselect_)}},
    // optional int32 random_seed = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.random_seed_), 10>(),
     {80, 10, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.random_seed_)}},
    // optional int32 mousedx = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.mousedx_), 11>(),
     {88, 11, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.mousedx_)}},
    // optional int32 mousedy = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.mousedy_), 12>(),
     {96, 12, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.mousedy_)}},
    // optional bool hasbeenpredicted = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CBaseUserCmdPB, _impl_.hasbeenpredicted_), 13>(),
     {104, 13, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.hasbeenpredicted_)}},
    // optional uint32 pawn_entity_handle = 14 [default = 16777215];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.pawn_entity_handle_), 16>(),
     {112, 16, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.pawn_entity_handle_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .CSubtickMoveStep subtick_moves = 18;
    {::_pbi::TcParser::FastMtR2,
     {402, 63, 2, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.subtick_moves_)}},
    // optional bytes move_crc = 19;
    {::_pbi::TcParser::FastBS2,
     {410, 0, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.move_crc_)}},
    // optional uint32 consumed_server_angle_changes = 20;
    {::_pbi::TcParser::FastV32S2,
     {416, 14, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.consumed_server_angle_changes_)}},
    // optional int32 cmd_flags = 21;
    {::_pbi::TcParser::FastV32S2,
     {424, 15, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.cmd_flags_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 command_number = 1;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.command_number_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 tick_count = 2;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.tick_count_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .CInButtonStatePB buttons_pb = 3;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.buttons_pb_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .CMsgQAngle viewangles = 4;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.viewangles_), _Internal::kHasBitsOffset + 2, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional float forwardmove = 5;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.forwardmove_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float leftmove = 6;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.leftmove_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float upmove = 7;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.upmove_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional int32 impulse = 8;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.impulse_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 weaponselect = 9;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.weaponselect_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 random_seed = 10;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.random_seed_), _Internal::kHasBitsOffset + 10, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 mousedx = 11;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.mousedx_), _Internal::kHasBitsOffset + 11, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 mousedy = 12;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.mousedy_), _Internal::kHasBitsOffset + 12, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional bool hasbeenpredicted = 13;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.hasbeenpredicted_), _Internal::kHasBitsOffset + 13, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional uint32 pawn_entity_handle = 14 [default = 16777215];
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.pawn_entity_handle_), _Internal::kHasBitsOffset + 16, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated .CSubtickMoveStep subtick_moves = 18;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.subtick_moves_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional bytes move_crc = 19;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.move_crc_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint32 consumed_server_angle_changes = 20;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.consumed_server_angle_changes_), _Internal::kHasBitsOffset + 14, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional int32 cmd_flags = 21;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.cmd_flags_), _Internal::kHasBitsOffset + 15, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::CInButtonStatePB>()},
    {::_pbi::TcParser::GetTable<::CMsgQAngle>()},
    {::_pbi::TcParser::GetTable<::CSubtickMoveStep>()},
  }}, {{
  }},
};

::uint8_t* CBaseUserCmdPB::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CBaseUserCmdPB)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 command_number = 1;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_command_number(), target);
  }

  // optional int32 tick_count = 2;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_tick_count(), target);
  }

  // optional .CInButtonStatePB buttons_pb = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::buttons_pb(this),
        _Internal::buttons_pb(this).GetCachedSize(), target, stream);
  }

  // optional .CMsgQAngle viewangles = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::viewangles(this),
        _Internal::viewangles(this).GetCachedSize(), target, stream);
  }

  // optional float forwardmove = 5;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this->_internal_forwardmove(), target);
  }

  // optional float leftmove = 6;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        6, this->_internal_leftmove(), target);
  }

  // optional float upmove = 7;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        7, this->_internal_upmove(), target);
  }

  // optional int32 impulse = 8;
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<8>(
            stream, this->_internal_impulse(), target);
  }

  // optional int32 weaponselect = 9;
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<9>(
            stream, this->_internal_weaponselect(), target);
  }

  // optional int32 random_seed = 10;
  if (cached_has_bits & 0x00000400u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<10>(
            stream, this->_internal_random_seed(), target);
  }

  // optional int32 mousedx = 11;
  if (cached_has_bits & 0x00000800u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<11>(
            stream, this->_internal_mousedx(), target);
  }

  // optional int32 mousedy = 12;
  if (cached_has_bits & 0x00001000u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<12>(
            stream, this->_internal_mousedy(), target);
  }

  // optional bool hasbeenpredicted = 13;
  if (cached_has_bits & 0x00002000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        13, this->_internal_hasbeenpredicted(), target);
  }

  // optional uint32 pawn_entity_handle = 14 [default = 16777215];
  if (cached_has_bits & 0x00010000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        14, this->_internal_pawn_entity_handle(), target);
  }

  // repeated .CSubtickMoveStep subtick_moves = 18;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_subtick_moves_size()); i < n; i++) {
    const auto& repfield = this->_internal_subtick_moves().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(18, repfield, repfield.GetCachedSize(), target, stream);
  }

  // optional bytes move_crc = 19;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_move_crc();
    target = stream->WriteBytesMaybeAliased(19, _s, target);
  }

  // optional uint32 consumed_server_angle_changes = 20;
  if (cached_has_bits & 0x00004000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        20, this->_internal_consumed_server_angle_changes(), target);
  }

  // optional int32 cmd_flags = 21;
  if (cached_has_bits & 0x00008000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        21, this->_internal_cmd_flags(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CBaseUserCmdPB)
  return target;
}

::size_t CBaseUserCmdPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CBaseUserCmdPB)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CSubtickMoveStep subtick_moves = 18;
  total_size += 2UL * this->_internal_subtick_moves_size();
  for (const auto& msg : this->_internal_subtick_moves()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes move_crc = 19;
    if (cached_has_bits & 0x00000001u) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_move_crc());
    }

    // optional .CInButtonStatePB buttons_pb = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.buttons_pb_);
    }

    // optional .CMsgQAngle viewangles = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.viewangles_);
    }

    // optional int32 command_number = 1;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_command_number());
    }

    // optional int32 tick_count = 2;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_tick_count());
    }

    // optional float forwardmove = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += 5;
    }

    // optional float leftmove = 6;
    if (cached_has_bits & 0x00000040u) {
      total_size += 5;
    }

    // optional float upmove = 7;
    if (cached_has_bits & 0x00000080u) {
      total_size += 5;
    }

  }
  if (cached_has_bits & 0x0000ff00u) {
    // optional int32 impulse = 8;
    if (cached_has_bits & 0x00000100u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_impulse());
    }

    // optional int32 weaponselect = 9;
    if (cached_has_bits & 0x00000200u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_weaponselect());
    }

    // optional int32 random_seed = 10;
    if (cached_has_bits & 0x00000400u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_random_seed());
    }

    // optional int32 mousedx = 11;
    if (cached_has_bits & 0x00000800u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_mousedx());
    }

    // optional int32 mousedy = 12;
    if (cached_has_bits & 0x00001000u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_mousedy());
    }

    // optional bool hasbeenpredicted = 13;
    if (cached_has_bits & 0x00002000u) {
      total_size += 2;
    }

    // optional uint32 consumed_server_angle_changes = 20;
    if (cached_has_bits & 0x00004000u) {
      total_size += 2 + ::_pbi::WireFormatLite::UInt32Size(
                                      this->_internal_consumed_server_angle_changes());
    }

    // optional int32 cmd_flags = 21;
    if (cached_has_bits & 0x00008000u) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this->_internal_cmd_flags());
    }

  }
  // optional uint32 pawn_entity_handle = 14 [default = 16777215];
  if (cached_has_bits & 0x00010000u) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_pawn_entity_handle());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CBaseUserCmdPB::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    CBaseUserCmdPB::MergeImpl
};
const ::google::protobuf::Message::ClassData*CBaseUserCmdPB::GetClassData() const { return &_class_data_; }


void CBaseUserCmdPB::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CBaseUserCmdPB*>(&to_msg);
  auto& from = static_cast<const CBaseUserCmdPB&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CBaseUserCmdPB)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_subtick_moves()->MergeFrom(from._internal_subtick_moves());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_move_crc(from._internal_move_crc());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_buttons_pb()->::CInButtonStatePB::MergeFrom(
          from._internal_buttons_pb());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_viewangles()->::CMsgQAngle::MergeFrom(
          from._internal_viewangles());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.command_number_ = from._impl_.command_number_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.tick_count_ = from._impl_.tick_count_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.forwardmove_ = from._impl_.forwardmove_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.leftmove_ = from._impl_.leftmove_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.upmove_ = from._impl_.upmove_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_impl_.impulse_ = from._impl_.impulse_;
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.weaponselect_ = from._impl_.weaponselect_;
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_impl_.random_seed_ = from._impl_.random_seed_;
    }
    if (cached_has_bits & 0x00000800u) {
      _this->_impl_.mousedx_ = from._impl_.mousedx_;
    }
    if (cached_has_bits & 0x00001000u) {
      _this->_impl_.mousedy_ = from._impl_.mousedy_;
    }
    if (cached_has_bits & 0x00002000u) {
      _this->_impl_.hasbeenpredicted_ = from._impl_.hasbeenpredicted_;
    }
    if (cached_has_bits & 0x00004000u) {
      _this->_impl_.consumed_server_angle_changes_ = from._impl_.consumed_server_angle_changes_;
    }
    if (cached_has_bits & 0x00008000u) {
      _this->_impl_.cmd_flags_ = from._impl_.cmd_flags_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00010000u) {
    _this->_internal_set_pawn_entity_handle(from._internal_pawn_entity_handle());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CBaseUserCmdPB::CopyFrom(const CBaseUserCmdPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CBaseUserCmdPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CBaseUserCmdPB::IsInitialized() const {
  return true;
}

void CBaseUserCmdPB::InternalSwap(CBaseUserCmdPB* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.subtick_moves_.InternalSwap(&other->_impl_.subtick_moves_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.move_crc_, lhs_arena,
                                       &other->_impl_.move_crc_, rhs_arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.pawn_entity_handle_)
      + sizeof(CBaseUserCmdPB::_impl_.pawn_entity_handle_)
      - PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.buttons_pb_)>(
          reinterpret_cast<char*>(&_impl_.buttons_pb_),
          reinterpret_cast<char*>(&other->_impl_.buttons_pb_));
}

::google::protobuf::Metadata CBaseUserCmdPB::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_usercmd_2eproto_getter, &descriptor_table_usercmd_2eproto_once,
      file_level_metadata_usercmd_2eproto[2]);
}
// ===================================================================

class CUserCmdBasePB::_Internal {
 public:
  using HasBits = decltype(std::declval<CUserCmdBasePB>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CUserCmdBasePB, _impl_._has_bits_);
  static const ::CBaseUserCmdPB& base(const CUserCmdBasePB* msg);
  static void set_has_base(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::CBaseUserCmdPB& CUserCmdBasePB::_Internal::base(const CUserCmdBasePB* msg) {
  return *msg->_impl_.base_;
}
CUserCmdBasePB::CUserCmdBasePB(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CUserCmdBasePB)
}
CUserCmdBasePB::CUserCmdBasePB(const CUserCmdBasePB& from) : ::google::protobuf::Message() {
  CUserCmdBasePB* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.base_){nullptr},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.base_ = new ::CBaseUserCmdPB(*from._impl_.base_);
  }

  // @@protoc_insertion_point(copy_constructor:CUserCmdBasePB)
}
inline void CUserCmdBasePB::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.base_){nullptr},
  };
}
CUserCmdBasePB::~CUserCmdBasePB() {
  // @@protoc_insertion_point(destructor:CUserCmdBasePB)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CUserCmdBasePB::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.base_;
}
void CUserCmdBasePB::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CUserCmdBasePB::Clear() {
// @@protoc_insertion_point(message_clear_start:CUserCmdBasePB)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.base_ != nullptr);
    _impl_.base_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CUserCmdBasePB::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> CUserCmdBasePB::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CUserCmdBasePB, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CUserCmdBasePB_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional .CBaseUserCmdPB base = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CUserCmdBasePB, _impl_.base_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .CBaseUserCmdPB base = 1;
    {PROTOBUF_FIELD_OFFSET(CUserCmdBasePB, _impl_.base_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::CBaseUserCmdPB>()},
  }}, {{
  }},
};

::uint8_t* CUserCmdBasePB::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CUserCmdBasePB)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .CBaseUserCmdPB base = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::base(this),
        _Internal::base(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUserCmdBasePB)
  return target;
}

::size_t CUserCmdBasePB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CUserCmdBasePB)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .CBaseUserCmdPB base = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.base_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CUserCmdBasePB::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    CUserCmdBasePB::MergeImpl
};
const ::google::protobuf::Message::ClassData*CUserCmdBasePB::GetClassData() const { return &_class_data_; }


void CUserCmdBasePB::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CUserCmdBasePB*>(&to_msg);
  auto& from = static_cast<const CUserCmdBasePB&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CUserCmdBasePB)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_base()->::CBaseUserCmdPB::MergeFrom(
        from._internal_base());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CUserCmdBasePB::CopyFrom(const CUserCmdBasePB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CUserCmdBasePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CUserCmdBasePB::IsInitialized() const {
  return true;
}

void CUserCmdBasePB::InternalSwap(CUserCmdBasePB* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.base_, other->_impl_.base_);
}

::google::protobuf::Metadata CUserCmdBasePB::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_usercmd_2eproto_getter, &descriptor_table_usercmd_2eproto_once,
      file_level_metadata_usercmd_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
