// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: valveextensions.proto

#include "valveextensions.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_valveextensions_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_valveextensions_2eproto = nullptr;
const ::uint32_t TableStruct_valveextensions_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_valveextensions_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\025valveextensions.proto\032 google/protobuf"
    "/descriptor.proto:\?\n\017valve_map_field\022\035.g"
    "oogle.protobuf.FieldOptions\030\310\334\003 \001(\010:\005fal"
    "se:=\n\rvalve_map_key\022\035.google.protobuf.Fi"
    "eldOptions\030\311\334\003 \001(\010:\005false:=\n\021diff_encode"
    "_field\022\035.google.protobuf.FieldOptions\030\312\334"
    "\003 \001(\005:\0010:<\n\014delta_ignore\022\035.google.protob"
    "uf.FieldOptions\030\313\334\003 \001(\010:\005false:\?\n\023steamm"
    "l_max_entries\022\035.google.protobuf.FieldOpt"
    "ions\030\314\334\003 \001(\r:\0010:D\n\024steamml_is_timestamp\022"
    "\035.google.protobuf.FieldOptions\030\315\334\003 \001(\010:\005"
    "false:<\n\020steamlearn_count\022\035.google.proto"
    "buf.FieldOptions\030\316\334\003 \001(\r:\0010:@\n\024schema_fr"
    "iendly_name\022!.google.protobuf.EnumValueO"
    "ptions\030\350\007 \001(\t:>\n\022schema_description\022!.go"
    "ogle.protobuf.EnumValueOptions\030\351\007 \001(\t:F\n"
    "\032schema_suppress_enumerator\022!.google.pro"
    "tobuf.EnumValueOptions\030\352\007 \001(\010"
};
static const ::_pbi::DescriptorTable* const descriptor_table_valveextensions_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_valveextensions_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_valveextensions_2eproto = {
    false,
    false,
    709,
    descriptor_table_protodef_valveextensions_2eproto,
    "valveextensions.proto",
    &descriptor_table_valveextensions_2eproto_once,
    descriptor_table_valveextensions_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_valveextensions_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_valveextensions_2eproto,
    file_level_service_descriptors_valveextensions_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_valveextensions_2eproto_getter() {
  return &descriptor_table_valveextensions_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_valveextensions_2eproto(&descriptor_table_valveextensions_2eproto);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>
  valve_map_field(kValveMapFieldFieldNumber, false, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>
  valve_map_key(kValveMapKeyFieldNumber, false, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::int32_t >, 5, false>
  diff_encode_field(kDiffEncodeFieldFieldNumber, 0, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>
  delta_ignore(kDeltaIgnoreFieldNumber, false, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::uint32_t >, 13, false>
  steamml_max_entries(kSteammlMaxEntriesFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>
  steamml_is_timestamp(kSteammlIsTimestampFieldNumber, false, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::uint32_t >, 13, false>
  steamlearn_count(kSteamlearnCountFieldNumber, 0u, nullptr);
const std::string schema_friendly_name_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false>
  schema_friendly_name(kSchemaFriendlyNameFieldNumber, schema_friendly_name_default, nullptr);
const std::string schema_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false>
  schema_description(kSchemaDescriptionFieldNumber, schema_description_default, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>
  schema_suppress_enumerator(kSchemaSuppressEnumeratorFieldNumber, false, nullptr);
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
